
ds_list_destroy(log)
ds_list_destroy(input_log)
ds_list_destroy(error_log)
ds_list_destroy(command_log)
ds_list_destroy(display_list)
ds_list_destroy(command_order)
ds_list_destroy(macro_list)
ds_list_destroy(suggestions)
ds_list_destroy(lite_suggestions)
ds_list_destroy(method_list)
ds_list_destroy(asset_list)
ds_list_destroy(elements)

ds_map_destroy(ds_types)
ds_map_destroy(commands)